# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fav_star}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brady Bouchard"]
  s.date = %q{2010-08-19}
  s.description = %q{fav_star provides a fairly straightforward module that allows you to keep track of which models your users have favourited.}
  s.email = %q{brady@ldawn.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.markdown",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "fav_star.gemspec",
     "lib/acts_as_faveable.rb",
     "lib/acts_as_faver.rb",
     "lib/fav_star.rb",
     "lib/generators/fav_star/fav_star_generator.rb",
     "lib/generators/fav_star/templates/fave.rb",
     "lib/generators/fav_star/templates/migration.rb"
  ]
  s.homepage = %q{http://github.com/brady8/favstar}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Mark your ActiveRecord models as favourites with only a couple of lines of code.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

