# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{objectreload-vote_fu}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Jackson", "Cosmin Radoi", "Bence Nagy", "Rob Maddox", "Wojciech Wnętrzak"]
  s.date = %q{2010-03-24}
  s.description = %q{VoteFu provides the ability to have multiple voting entities on an arbitrary number of models in ActiveRecord.}
  s.email = %q{gems@objectreload.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.markdown",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "examples/routes.rb",
     "examples/users_controller.rb",
     "examples/voteable.html.erb",
     "examples/voteable.rb",
     "examples/voteables_controller.rb",
     "examples/votes/_voteable_vote.html.erb",
     "examples/votes/create.rjs",
     "examples/votes_controller.rb",
     "generators/vote_fu/templates/migration.rb",
     "generators/vote_fu/templates/vote.rb",
     "generators/vote_fu/vote_fu_generator.rb",
     "lib/acts_as_voteable.rb",
     "lib/acts_as_voter.rb",
     "lib/has_karma.rb",
     "lib/vote_fu.rb",
     "rails/init.rb",
     "test/vote_fu_test.rb"
  ]
  s.homepage = %q{http://github.com/objectreload/vote_fu}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Voting for ActiveRecord with multiple vote sources and advanced features.}
  s.test_files = [
    "test/vote_fu_test.rb",
     "examples/routes.rb",
     "examples/users_controller.rb",
     "examples/voteable.rb",
     "examples/voteables_controller.rb",
     "examples/votes_controller.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

